---
title: "Code for the representation of indices results"
author: "Mar Llaberia-Reobledillo, Juan A. Balbuena, Volodimir Sarabeev, Cristina Llopis-Belenguer"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE}
library(ggplot2)
```

# CONNECTANCE INDEX
```{r, echo=TRUE}

#connectance
color <- rep(c("Sea of Azov","Sea of Japan"), each = 4)
x <- rep(c("Whole","Actively transmitted","Passively transmitted","Ectoparasites"),times = 2)
y <- c(0.13218, 0.18534, 0.14006, 0.32564,
       0.31746, 0.36182, 0.28776, 0.39679)
min <- c(0.1260867, 0.1775452, 0.1310440, 0.3137242,
         0.3041492, 0.3468139, 0.2695431, 0.3787741)
max <- c(0.1421748, 0.2048869, 0.1542897, 0.3371604,
         0.3655938, 0.4795844, 0.3070707, 0.5414562)
df <- data.frame(x, y, color, min, max)


ggplot(df, aes(x=x, y=y, fill=color)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=min, ymax=max), width=.2,
                position=position_dodge(.9)) + theme_bw() +
  labs(fill = "", x = "", y = "Connectance")+
  theme (text = element_text(size=10))

```

# WEIGHTED NESTEDNESS INDEX
```{r}
#WNODF 

color <- rep(c("Sea of Azov","Sea of Japan"), each = 4)
x <- rep(c("Whole","Actively transmitted","Passively transmitted","Ectoparasites"),times = 2)
y <- c(-2.974539, 6.535616, -11.22251, 8.133092,
       -14.27871, -4.315204, -24.1363, -0.7750652)
min <- c(-6.26471856, 3.297365, -12.935694, 4.172035,
        -16.37680, -6.451115, -25.95706, -3.416936)
max <- c(0.06678918, 9.526102, -9.495149, 11.787828,
        -12.15434, -2.436728, -22.16251, 1.754734)
df <- data.frame(x,y,color,min,max)


ggplot(df, aes(x=x, y=y, fill=color)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=min, ymax=max), width=.2,
                position=position_dodge(.9)) + theme_bw() +
  labs(fill = "", x = "Network", y = "Standardised WNODF")+
  theme (text = element_text(size=10))

```

# MODULARITY INDEX
```{r}
#modularidad
color <- rep(c("Invaded area","Native area"), each = 4)
x <- rep(c("Whole","Actively transmitted","Passively transmitted","Ectoparasites"),times = 2)
y <- c(29.2585, 20.99315, 14.75034, 17.58154,
       50.3223, 33.45454,	29.76626, 8.523125)
min <- c(19.41111, 8.029887, 8.890733, 3.269184,
         39.09475, 22.62603, 21.95252, 6.302498)
max <- c(33.26089, 25.260363, 18.610693, 21.253723,
         58.27906, 43.92675, 40.17420, 10.840497)
df <- data.frame(x,y,color,min,max)


ggplot(df, aes(x=x, y=y, fill=color)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=min, ymax=max), width=.2,
                position=position_dodge(.9)) + theme_bw() +
  labs(fill = "", x = "Network", y = "Standardised Q")+
  theme (text = element_text(size=10))

```

